apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev1
  name: test-gclient-deployment
  labels:
    app: test-gclient
    service: test-gclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gclient
  template:
    metadata:
      labels:
        app: test-gclient
        type: grpc-test-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - grpc-test-app
            topologyKey: kubernetes.io/hostname
      containers:
      - name: test-gclient
        imagePullPolicy: Always
        env:
        - name: ADDR
          value: test-gserver-headless:9090
        - name: DNS
          value: "true"
        - name: FREQUENCY
          value: "1"
        image: albertocsm/test-gclient:latest
        ports:
        - containerPort: 9090