apiVersion: v1
kind: Service
metadata:
  namespace: dev1
  name: test-gclient
  labels:
    app: test-gclient
  annotations:
    prometheus.io/port: "8081"
    prometheus.io/scrape: "true"
spec:
  selector:
    app: test-gclient
  ports:
  - name: prom
    port: 8081
    protocol: TCP
    targetPort: 8081
  type: ClusterIP