apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: dev1
  name: test-gserver-deployment
  labels:
    app: test-gserver
    services: test-gserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-gserver
  template:
    metadata:
      labels:
        app: test-gserver
        type: grpc-test-app
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: type
                operator: In
                values:
                - grpc-test-app
            topologyKey: kubernetes.io/hostname
      nodeSelector:
        beta.kubernetes.io/instance-type: n1-highcpu-8
      containers:
      - name: test-gserver
        image: albertocsm/test-gserver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090