apiVersion: v1
kind: Service
metadata:
  namespace: dev1
  name: test-gserver-headless
  labels:
    app: test-gserver-headless
spec:
  selector:
    app: test-gserver
  ports:
  - name: svc
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: ClusterIP
  clusterIP: None